name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of MusicDJ are you running?
      placeholder: v1.2.2-beta
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS/Browser version
      placeholder: Eg. Chrome 92 on Windows 10 19043
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: This is optional.
      placeholder: Eg. Pixel 4
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
